### ISSUE TITLE
I made a bot from this code

### ISSUE THREAD

**Issue by phillipbruh** [VirescentOverlord/Moby-Max-Hack#1]
Hi made a moby max concept bot from your code it can answer multiple choice and answer text questions with multi text support

Code:
https://github.com/phillipbruh/snowplus/blob/main/mobymaxbotconceptsource

Bookmarklet(untested):
https://github.com/phillipbruh/snowplus/blob/main/mobymaxbotconceptbookmarklet

**Comment by VirescentOverlord** [comment]
javascript:req = new XMLHttpRequest();
req.open('GET', 'https://raw.githubusercontent.com/phillipbruh/snowplus/main/mobymaxbotconceptsource');
req.onload = function() {
  eval(this.responseText + 'addJQuery(slide);');
};
req.send();
alert("Made By Virescent Overlord and Phillipbruh")
